config/routes.rb
Rails.application.routes.draw do
  
  
  resources :sessions
  
  #named routes
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  get    "logout" => "sessions#destroy"
  
  
  resources :chefs
  
  #named routes 
  get "register" => "chefs#new"
  
  resources :recipes do
    member do 
      post 'like'
    end 
  end 
  
  
  get "home" => 'pages#home'
  
  root "pages#home"

end 

app/models/chef.rb
class Chef < ActiveRecord::Base
  #before any object is saved all emails with be downcased 
  before_save { self.email = email.downcase }
  has_many :recipes 
  has_many :likes
  validates :chefname, presence: true, length: { in: 3..40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { in: 1..105 }, uniqueness: { case_sensitive: false },
                                                         format: { with: VALID_EMAIL_REGEX }
                                                         
  has_secure_password

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe 
  
  validates_uniqueness_of :chef, scope: :recipe 
end 

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes 

  validates :chef_id, presence: true 
  validates :name, presence: true, length: { in: 3..100 }
  validates :summary, presence: true, length: { in: 10..150 }
  validates :description, presence: true, length: { in: 20..50 }
  
  mount_uploader :picture, PictureUploader
  validate :picture_size
  default_scope -> { order(updated_at: :desc) }
  
  def thumbs_up_total 
    self.likes.where(like: true).size
  end 
  
  def thumbs_down_total
    self.likes.where(like: false).size 
  end 
  
  #server sid validations for picture size
  private 
    def picture_size
      if picture.size > 5.megabytes 
        errors.add(:picture, "should be less than 5MB")
      end 
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #available to our views now
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end 
  
  #check to see if current user logged in
  def logged_in?
    !!current_user
  end 
  
  def require_user 
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path 
    end 
  end 
    
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  
  def index 
    @chefs = Chef.all.paginate(page: params[:page], per_page: 2)
  end 
  
  def show 
    @recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
  end 
  
  def new 
    @chef = Chef.new 
  end 
  
  def create 
    @chef = Chef.new(chef_params)
    if @chef.save 
      flash[:success] = "Your account has been created succesfully!"
      session[:chef_id] = @chef.id
      redirect_to recipes_path 
    else 
      flash.now[:error] = "Please try again"
      render :new
    end 
  end 
  
  def edit 
  
  end 
  
  def update
    if @chef.update(chef_params)
      flash[:success] = "Chef has been updated"
      redirect_to chef_path(@chef)
    else
      flash.now[:error] ="Error editing the form"
      render :edit 
    end 
  end 
  
  private 
    def chef_params
      params.require(:chef).permit(:chefname, :email, :password)
    end 
    
    def require_same_user
      if current_user != @chef
        flash[:danger] = "You can only edit your own profile"
        redirect_to root_path
      end 
    end 
    
    def set_chef 
      @chef = Chef.find(params[:id])
    end 
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    if logged_in?
      redirect_to recipes_path
    end 
  end
  
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :show, :like ]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update ]
  
  def index 
    @recipes = Recipe.paginate(page: params[:page], per_page: 4) 
  end 
  
  def show
  
  end 
  
  def new 
    @recipe = Recipe.new
  end 
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_user
    if @recipe.save
      flash[:success] = "Your recipe was created successfully"
      redirect_to recipes_path 
    else 
      flash.now[:error] = "Error with your form"
      render :new 
    end
    
  end 
  
  def edit 
  
  end 
  
  def update 
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe has been successfully updated"
      redirect_to recipe_path(@recipe)
    else 
      flash.now[:error] = "You have an error with your form"
      render :edit
    end 
  end 
  
  def destroy 
  end 
  
  def like 
    @like = Like.new(like: params[:like], chef: current_user, recipe: @recipe)
    if @like.valid?
      if @like.save
        flash[:success] = "Your selection was successful"
        #user stays on the page where the like is made 
        redirect_to :back 
      else 
        flash[:"you can only like/dislike a recipe once"]
        redirect_to :back 
      end
    end 
    
  end
  
  private 
    def recipe_params 
      params.require(:recipe).permit(:name, :summary, :description, :id, :picture)
    end 
   
    def require_same_user
      if current_user != @recipe.chef
        flash[:danger] = "You can only edit your own profile"
        redirect_to recipes_path 
      end 
    end 
    
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end 
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end 
  
  def create
    # check to see if email is in database and brin up that user
    chef = Chef.find_by_email(params[:email])
    if chef.valid? && chef.authenticate(params[:password])
      session[:chef_id] = chef.id 
      flash["success"] = "You are logged in"
      redirect_to recipes_path 
    else 
      flash.now[:error] = "Please try again"
      render :new
    end 
    # authenticate that user with the password provided 
  end 
  
  def destroy
    #set user session to nil
    session[:chef_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
    #redirect to home
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for (chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end 
  
   def error_messages_for(object)
      render partial: "shared/errors", locals: { object: object }
   end 
   
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chefs/_form.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for@chef do |f| %>
    
        <%= f.label :chefname %> <br />
        <%= f.text_field :chefname %>
   
      
    
        <%= f.label :email %> <br />
        <%= f.email_field :email %>
     
      
     
        <%= f.label :password %> <br />
        <%= f.password_field :password  %>
        
     
        <%= f.submit (@chef.new_record? ? "Register": "Edit Profile") , class: "btn btn-success" %>
      
      <% end %>
      </div>
    </div>
</div>

app/views/chefs/edit.html.erb
<%= render "shared/page_title", title: "Edit your profile" %>
<%= render "form" %>

  

app/views/chefs/index.html.erb
<%= render "shared/page_title", title: "All Chefs" %>

<ul class="nav nav-tabs">
  <li> 
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li class="active">
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate @chefs %>
  </div>
</div>


<% @chefs.each do |chef| %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
      <%= link_to gravatar_for(chef, size: 200), chef_path(chef) %>
      <p>
        <h5> Chef name: <%= chef.chefname %></h5>
      </p>
    </div>
  </div>
<% end %>

<%= will_paginate @chefs %>




  
 

app/views/chefs/new.html.erb
<%= render "shared/page_title", title: "Register your account" %>
<%= render "form" %>

  

app/views/chefs/show.html.erb
<%= render "shared/page_title", title: "Chef: #{@chef.chefname}" %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @chef, size: 200 %>
   <hr />
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <h3> <em> Recipes </em></h3>
    <%= will_paginate @recipes %>
  </div>
</div>


<% @recipes.each do |recipe| %>
   <div class="row">
     <div class="col-lg-6 well col-lg-offset-3">
       <h4> <%= link_to recipe.name, recipe_path(recipe) %> </h4>
          <p> <%= recipe.summary %> </p>
          <p>
            <%= link_to "Edit Recipe", edit_recipe_path(recipe) %>
          </p>
          <p>
          <span class="quiet"><small> created: <%= time_ago_in_words(recipe.created_at) %> </small></span></span>
          <span class="quiet"><small> updated: <%= time_ago_in_words(recipe.updated_at) %> </small></span></span>
          </p>
          <div class="pull-right">
            <%= link_to like_recipe_path(recipe, like: true ), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
          <% end %> &nbsp &nbsp &nbsp &nbsp
          
          <%= link_to like_recipe_path(recipe, like: false ), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
          <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p> &copy; MyRecipes 2015 </p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class= "col-md-12">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"> <%= message %>
          <a class="class" data-dismiss="alert"> &#215;</a>
        </div>
      <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Bon Appetit", root_path, class: "btn btn-lg btn-success", id: "logo" %> 
      <div class="nav-item">
        <%= link_to "link1", "", class: "btn btn-default btn-warning" %>
      </div>
      <div class="nav-item">
        <%= link_to "link2", "", class: "btn btn-default btn-warning" %>
      </div>
    <% if logged_in? %>
      <div class="nav-item">
        <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-warning" %>
      </div>
      <ul class="nav-item">
        <li class="dropdown">
          <%= link_to "#", class: "btn btn-default btn-danger-dropdown-toggle", "data-toggle" => "dropdown" do %>
            <%= current_user.chefname %> <b class="caret"> </b>
          <% end %>
          <Ul class="dropdown-menu">
            <li> <%= link_to "View Profile", chef_path(current_user) %>      </li>
            <li> <%= link_to "Edit Profile", edit_chef_path(current_user) %> </li>
            <li class="divider"></li>
            <li> <%= link_to "Logout", logout_path, class: "btn btn-default btn-danger" %> </li>
          </Ul>
        </li>
      </ul>
      <% else %>
        <div class="nav-item">
          <%= link_to "Log in", new_session_path, class: "btn btn-default btn-success" %>
        </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bon Appetit </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navigation" %> 
  <div class="container">
    <%= yield %> 
    <%= render "layouts/footer" %>
   </div> 
</body>

</html>

app/views/pages/home.html.erb
<div class=" center jumbotron">
    <h1> Welcome to Bon Appetit </h1>
    
    <h2> </h2>
    
    <%= link_to "Sign up now!", new_chef_path, class: "btn btn-lg btn-success" %>
</div>
<div class="row">
    <div class="col-lg-4">
        <h3 class="midrow">
            Sign into your account 
        </h3>
            
        <h2 class="left">
            Add/update your recipes/create reviews/like-dislike recipes and much much more!
        </h2>
        <p> <%= link_to "Log into your account", new_session_path, class: "btn btn-warning btn-small" %></p>
    </div>
    
     <div class="col-lg-4">
        <h3 class="midrow">
            View Recipes as Guest User
        </h3>
            
        <h2 class="left">
            Browse and view recipes as a guest and Sign up later 
        </h2>
        <p> <%= link_to "Log in", recipes_path, class: "btn btn-warning btn-small" %></p>
    </div>
    
     <div class="col-lg-4">
        <h3 class="midrow">
            View Recipes as Guest User
        </h3>
            
        <h2 class="left">
            Browse and view recipes as a guest and Sign up later 
        </h2>
        <p> <%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
    </div>
</div>

app/views/recipes/_form.html.erb
<div class="well col-md-8 col-md-offset-2">
    <%= form_for(@recipe, html: { multipart: true }) do |f| %>
    
        <%= f.label :name %> <br />
        <%= f.text_field :name %>
   
      
    
        <%= f.label :summary %> <br />
        <%= f.text_field :summary %>
     
      
     
        <%= f.label :description %> <br />
        <%= f.text_area :description, rows: 10 %>
        
        <span class="picture"> 
             <%= f.file_field :picture, accept: "image/jpeg, image/gif,image/png" %>
        </span>
     
        <%= f.submit (@recipe.new_record? ? "Create New Recipe": "Edit Recipe") , class: "btn btn-success" %>
      
      <% end %>
    </div>
</div>

<script type="text/javascript">
    $('#recipe.picture').bind('change', function() {
        
        size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximium file size is 5MB. Please choose a smaller size');
        }
    });
</script>

app/views/recipes/edit.html.erb
<%= render "shared/page_title", title: "Edit Recipe"  %>
<%= render "form" %>

app/views/recipes/index.html.erb
<%= render "shared/page_title", title: "All Recipes" %>

<ul class="nav nav-tabs">
  <li class="active"> 
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate %>

<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
            <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
            <h5> Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>
    
  <div class="col-lg-8 well">
    <h4> <%= link_to recipe.name, recipe_path(recipe) %> </h4>
      <p> <%= recipe.summary %> </p>
      <p>
        <%= link_to "Edit Recipe", edit_recipe_path(recipe) %>
      </p>
      <p>
      <span class="quiet"><small> created: <%= time_ago_in_words(recipe.created_at) %> </small></span></span>
      <span class="quiet"><small> updated: <%= time_ago_in_words(recipe.updated_at) %> </small></span></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true ), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
      <% end %> &nbsp &nbsp &nbsp &nbsp
      
      <%= link_to like_recipe_path(recipe, like: false ), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
      <% end %>
    </div>
</div>
  
  <div class="col-md-4">
    <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
  </div>
  
  </div>
  
  <hr />
  
<% end %>

<%= will_paginate %>


  

app/views/recipes/new.html.erb
<%= render "shared/page_title", title: "Create a New Recipe" %>
<%= render "form" %>

  

app/views/recipes/show.html.erb
<%= render "shared/page_title", title: @recipe.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to gravatar_for(@recipe.chef, size: 200), chef_path(@recipe.chef) %>
    <p>
      <h5> Brought to you by: <%= @recipe.chef.chefname %> </h5>
    </p>
  </div>
  <div class="col-md-8">
    <% if logged_in? and @recipe.chef == current_user %>
      <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
    <% end %>
    <h3> <%=  @recipe.summary %> </h3>
    <div class="show-recipe">
      <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
    </div>
    <div class="well">
      <p>
        <strong> Steps </strong> 
      </p>
        <%= simple_format(@recipe.description) %> 
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true ), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @recipe.thumbs_up_total %>
        <% end %> &nbsp &nbsp &nbsp &nbsp
        
        <%= link_to like_recipe_path(@recipe, like: false ), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    
    
  </div>
</div>

<h5> <%= link_to "Return to Recipes Listing", recipes_path, class: "btn btn-warning btn-small" %> </h5>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5> Please correct the following errors</h5>
        <% object.errors.full_messages.each do |error| %>
          <ul>
            <li> <%= error %></li>
          </ul>
        <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1> <%= title %> </h1>
  <hr />
</p>